### ISSUE TITLE
Batch Insight crash if instrumentation key is missing

### ISSUE THREAD

**Issue by Gaploid** [Azure/batch-insights#36]
Hi, any ideas why it does not work on Ubuntu 16.04?

Here is a log:
```
2019-03-15 10:41:49 (12.1 MB/s) - './batch-insights' saved [7474080/7474080]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6719b9]

goroutine 1 [running]:
github.com/Azure/batch-insights/pkg.hideSecret(...)
	/home/vsts/work/1/s/pkg/config.go:148
github.com/Azure/batch-insights/pkg.UserConfig.Print(0xc000010d40, 0xc000010d50, 0x0, 0xc000010da0, 0x1, 0x1, 0xc000018578, 0xc000010db0, 0x1, 0x1)
	/home/vsts/work/1/s/pkg/config.go:32 +0x159
main.main()
	/home/vsts/work/1/s/main.go:94 +0x43e
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
```

**Comment by timotheeguerin** [comment]
Hi, Which version are you using?

**Comment by Gaploid** [comment]
@timotheeguerin  latest, 1.3

**Comment by timotheeguerin** [comment]
I see, does reverting to a previous version fix the issue? How are you providing the instrumentation key, this seems to be the issue here.

**Comment by Gaploid** [comment]
Simple start task:
```
                EnvironmentSetting app_id = new EnvironmentSetting("APP_INSIGHTS_APP_ID", APP_INSIGHTS_APP_ID);
                EnvironmentSetting app_key = new EnvironmentSetting("APP_INSIGHTS_KEY", APP_INSIGHTS_KEY);
                EnvironmentSetting app_url = new EnvironmentSetting("BATCH_INSIGHTS_DOWNLOAD_URL", BATCH_INSIGHTS_DOWNLOAD_URL);

                List<EnvironmentSetting> env_list = new List<EnvironmentSetting>();
                env_list.Add(app_id);
                env_list.Add(app_key);
                env_list.Add(app_url);

                //// Assign the pool preparation task to the job
                StartTask task = new StartTask("/bin/sh -c ./initscript.sh");
                task.EnvironmentSettings = env_list;
                task.ResourceFiles = files;
                task.UserIdentity = new UserIdentity(new AutoUserSpecification(elevationLevel: ElevationLevel.Admin, scope: AutoUserScope.Pool));
                task.WaitForSuccess = true;
                pool.StartTask = task;
```

**Comment by timotheeguerin** [comment]
I believe the issue is with the name of the environment variable `APP_INSIGHTS_INSTRUMENTATION_KEY`, `APP_INSIGHTS_KEY` was deprecated a while back.
Seems like however it doesn't fail nicely when the key is missing, will update that.

**Comment by Gaploid** [comment]
Ouch, thanks for the hint, I will check that. Why did you change the name of the variable?:)

**Comment by timotheeguerin** [comment]
People were mixing up the instrumentation key and the keys you can create for API usage(As that's on the same page as the application ID)
